[package]
name = "byond-types"
version = "0.1.0"
authors = ["Rob Bailey (actioninja@criticalaction.net)"]
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
duplicate = "1.0"